from dotenv import load_dotenv
import requests
from agents import (
    Agent,
    Runner,
    trace,
    function_tool,
    ModelSettings,
    set_default_openai_api,
)
import os
import asyncio
import smtplib
from email.message import EmailMessage

load_dotenv(override=True)

MODEL_NAME = "gemini-3.5-flash-lite"


# DeepSeek API

# deepseek_api_key = os.getenv("DEEPSEEK_API_KEY")

# if deepseek_api_key:
#     print(f"DeepSeek API Key exists and begins {deepseek_api_key[:8]}")

#     os.environ["OPENAI_API_KEY"] = deepseek_api_key
#     os.environ["OPENAI_BASE_URL"] = "https://api.deepseek.com"

# else:
#     print("DEEPSEEK_API_KEY not set")

gemini_api_key = os.getenv("GEMINI_API_KEY")

if gemini_api_key:
    print(f"Gemini API Key exists and begins {gemini_api_key[:8]}")
    os.environ["OPENAI_API_KEY"] = gemini_api_key
    os.environ["OPENAI_BASE_URL"] = (
        "https://generativelanguage.googleapis.com/v1beta/openai/"
    )
else:
    print("GEMINI_API_KEY not set")


set_default_openai_api("chat_completions")


# Email configuration

EMAIL_ADDRESS = os.getenv("EMAIL_ADDRESS")
EMAIL_SMTP_SERVER = os.getenv("EMAIL_SMTP_SERVER")
EMAIL_APP_PASSWORD = os.getenv("EMAIL_APP_PASSWORD")

if EMAIL_ADDRESS:
    print("Email address is set")
else:
    print("Email address is not set")

if EMAIL_SMTP_SERVER:
    print("SMTP server is set")
else:
    print("SMTP server is not set")

if EMAIL_APP_PASSWORD:
    print("App password is set")
else:
    print("App password is not set")

USE_EMAIL = EMAIL_ADDRESS and EMAIL_SMTP_SERVER and EMAIL_APP_PASSWORD

if USE_EMAIL:
    print("Email is set up and we will try using it")
else:
    print("Email is not set up; we will send push notifications instead")


# Pushover

pushover_user = os.getenv("PUSHOVER_USER")
pushover_token = os.getenv("PUSHOVER_TOKEN")

pushover_url = "https://api.pushover.net/1/messages.json"

if pushover_user:
    if pushover_user.startswith("u"):
        print("Pushover user found and looks good")
    else:
        print("Pushover user found but doesn't start with u")
else:
    print("Pushover user not found")


if pushover_token:
    if pushover_token.startswith("a"):
        print("Pushover token found and looks good")
    else:
        print("Pushover token found but doesn't start with a")
else:
    print("Pushover token not found")


# Send email


def send_email(subject, text_body, html_body):
    """This function is use for send email to user"""

    msg = EmailMessage()

    msg["From"] = EMAIL_ADDRESS
    msg["To"] = EMAIL_ADDRESS
    msg["Subject"] = subject

    msg.set_content(text_body)
    msg.add_alternative(html_body, subtype="html")

    with smtplib.SMTP(EMAIL_SMTP_SERVER, 587) as server:
        server.starttls()
        server.login(EMAIL_ADDRESS, EMAIL_APP_PASSWORD)
        server.send_message(msg)


# Push notification


def push(message):
    print(f"Push: {message}")

    payload = {"user": pushover_user, "token": pushover_token, "message": message}

    requests.post(pushover_url, data=payload)


# Send message


def send_message(subject, text_body, html_body):
    if USE_EMAIL:
        send_email(subject, text_body, html_body)
    else:
        push(f"Subject: {subject}\n\n{text_body}")


# Agents

intro = """
You are an AI email assistant.

You help users by answering their questions and completing tasks through email.

You write clear, helpful emails.
"""

instructions1 = intro + "Your email style is professional, clear, and trustworthy."

instructions2 = intro + "Your email style is friendly, engaging, and conversational."

instructions3 = intro + "Your email style is concise, direct, and to the point."


sales_agent1 = Agent(
    name="Professional Sales Agent", instructions=instructions1, model=MODEL_NAME
)

sales_agent2 = Agent(
    name="Humorous Sales Agent", instructions=instructions2, model=MODEL_NAME
)

sales_agent3 = Agent(
    name="Executive Sales Agent", instructions=instructions3, model=MODEL_NAME
)


# Email picker

decision = """
You are the final email reviewer for an AI email assistant.

You will receive multiple candidate email responses generated by other agents.

Review all the options and choose the email that is most helpful and appropriate
for the user.

Choose the one that is:
- clear and easy to understand
- helpful and relevant to the user's message
- natural and human-sounding
- professional but not unnecessarily formal
- concise and direct
- most likely to satisfy the user

Do not explain your decision.
Do not compare the options.
Reply with the selected email only.
"""

email_picker = Agent(name="Email_picker", instructions=decision, model=MODEL_NAME)


# Test three agents + picker


async def main():

    message = "Write a cold sales email"

    results = await asyncio.gather(
        Runner.run(sales_agent1, message),
        Runner.run(sales_agent2, message),
        Runner.run(sales_agent3, message),
    )

    outputs = [result.final_output for result in results]

    emails = "Cold sales emails:\n\n" + "\n\nEmail:\n\n".join(outputs)

    # FIX: Runner.run() needs await
    best = await Runner.run(email_picker, emails)

    print(f"Best sales email:\n{best.final_output}")


# Send email tool


@function_tool
def send_email_tool(subject: str, text_body: str, html_body: str) -> str:
    """
    Send out an email with the given subject and body to all sales prospects

    Args:
        subject: The subject of the email
        text_body: The body of the email as plain text
        html_body: The HTML body of the email
    """

    send_message(subject, text_body, html_body)

    return "Email sent successfully"


# Agent as tools

description = """
Use this tool to write a sales email.
In the input, just instruct it to write a sales email.
"""

tool1 = sales_agent1.as_tool(
    tool_name="sales_email_writer_1", tool_description=description
)

tool2 = sales_agent2.as_tool(
    tool_name="sales_email_writer_2", tool_description=description
)

tool3 = sales_agent3.as_tool(
    tool_name="sales_email_writer_3", tool_description=description
)


tools = [tool1, tool2, tool3, send_email_tool]

print(tools)


instructions = """
You are a Sales Manager at ComplAI.
Your goal is to find the single best cold sales email using the sales_writer tools.
"""

task = """
Follow these steps:

1. Generate Drafts:
Use each of the three sales_email_writer tools to generate different email drafts.
Just instruct each to write a sales email; no further details are needed.
Do not proceed until all three drafts are ready, one from each tool.

2. Evaluate and Select:
Review the drafts and choose the single best email using your judgment of which one is most effective.

3. Use your tool to send the best email (and only the best email) to the user.
Only send 1 email.
"""


sales_manager = Agent(
    name="Sales Manager", instructions=instructions, tools=tools, model=MODEL_NAME
)

if __name__ == "__main__":
    asyncio.run(main())
